# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pIcxxWOndSq9ZcXjrpRXofk9mQCHp7_V
"""

import streamlit as st
import pandas as pd
import pickle
import os

# --- Configuration ---
MODEL_FILE = 'random_forest_model.pkl'

# --- Streamlit App Functions ---

def load_model(file_path):
    """Loads the pre-trained machine learning model."""
    if not os.path.exists(file_path):
        st.error(f"Error: Model file '{file_path}' not found in the current directory.")
        return None
    try:
        with open(file_path, 'rb') as file:
            model = pickle.load(file)
        return model
    except Exception as e:
        st.error(f"Error loading the model: {e}")
        return None

def main():
    """Main function to run the Streamlit app."""
    st.set_page_config(page_title="Supply Chain Late Delivery Predictor", layout="centered")
    st.title("📦 Supply Chain Late Delivery Predictor")
    st.markdown("Use the form below to input shipment details and predict the Late Delivery Status.")

    # 1. Load Model
    model = load_model(MODEL_FILE)
    if model is None:
        st.stop()

    # 2. Define Expected Features and Categorical Values

    # NOTE: These lists are derived from the uploaded 'logitech_supply_chain.csv'
    # and are assumed to be the categorical values the model was trained on.
    ROUTE_IDS = ['Domestic', 'Asia-EU', 'Asia-US', 'Europe-US']
    TRANSPORT_MODES = ['Truck', 'Sea', 'Air', 'Unknown']

    # Full list of features the model expects after one-hot encoding.
    # This MUST match the features the model was trained on exactly.
    MODEL_FEATURES = [
        'Supplier_Quality_Score',
        'Cost_Per_Unit',
        'Lead_Time_Days',
        'Route_ID_Asia-EU',
        'Route_ID_Asia-US',
        'Route_ID_Domestic',
        'Route_ID_Europe-US',
        'Transport_Mode_Air',
        'Transport_Mode_Sea',
        'Transport_Mode_Truck',
        'Transport_Mode_Unknown'
        # Add other engineered features here if the model was trained with them
        # e.g., 'Order_Month', 'Order_DayOfWeek', etc.
    ]

    # 3. Create Input Form
    with st.form("prediction_form"):
        st.header("Shipment Details")

        # --- Numerical Inputs ---
        col1, col2, col3 = st.columns(3)
        with col1:
            supplier_quality = st.number_input(
                "Supplier Quality Score (0.0 to 1.0)",
                min_value=0.0, max_value=1.0, value=0.5, step=0.01
            )
        with col2:
            cost_per_unit = st.number_input(
                "Cost Per Unit",
                min_value=0.0, value=150.0, step=10.0
            )
        with col3:
            lead_time = st.number_input(
                "Lead Time (Days)",
                min_value=1, value=10, step=1
            )

        # --- Categorical Inputs ---
        col4, col5 = st.columns(2)
        with col4:
            route_id = st.selectbox(
                "Route ID",
                options=ROUTE_IDS
            )
        with col5:
            transport_mode = st.selectbox(
                "Transport Mode",
                options=TRANSPORT_MODES
            )

        # 4. Prediction Button
        st.markdown("---")
        submitted = st.form_submit_button("Predict Late Delivery Status")

    # 5. Prediction Logic
    if submitted:
        # 5a. Create a DataFrame from the user input
        input_data = pd.DataFrame([{
            'Supplier_Quality_Score': supplier_quality,
            'Cost_Per_Unit': cost_per_Unit,
            'Lead_Time_Days': lead_time,
            'Route_ID': route_id,
            'Transport_Mode': transport_mode
        }])

        # 5b. Apply One-Hot Encoding
        input_data_encoded = pd.get_dummies(
            input_data,
            columns=['Route_ID', 'Transport_Mode'],
            drop_first=False # Keep all dummies to ensure all columns are present
        )

        # 5c. Align columns to match the training data
        # Add missing columns (for categories not selected) and reorder
        try:
            prediction_df = input_data_encoded.reindex(columns=MODEL_FEATURES, fill_value=0)

            # 5d. Make Prediction
            prediction = model.predict(prediction_df)
            prediction_proba = model.predict_proba(prediction_df)

            # 5e. Display Results
            st.subheader("Prediction Result")
            if prediction[0] == 1:
                st.error("🚨 Predicted Status: LATE DELIVERY")
                st.markdown(f"**Probability of Late Delivery:** $ {prediction_proba[0][1]:.2f} $")
            else:
                st.success("✅ Predicted Status: ON-TIME DELIVERY")
                st.markdown(f"**Probability of On-Time Delivery:** $ {prediction_proba[0][0]:.2f} $")

            st.balloons()

        except Exception as e:
            st.error(f"An error occurred during prediction. This may indicate a mismatch between the model's expected features and the features derived from the current inputs. Error: {e}")

if __name__ == "__main__":
    main()