# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pIcxxWOndSq9ZcXjrpRXofk9mQCHp7_V
"""

import streamlit as st
import pandas as pd
import pickle
import os
from datetime import date, timedelta

# --- Configuration ---
MODEL_FILE = 'logistic_regression_model.pkl'

# --- Streamlit App Functions ---

def load_model(file_path):
    """Loads the pre-trained machine learning model."""
    if not os.path.exists(file_path):
        st.error(f"Error: Model file '{file_path}' not found in the current directory.")
        return None
    try:
        with open(file_path, 'rb') as file:
            model = pickle.load(file)
        return model
    except Exception as e:
        st.error(f"Error loading the model. Please ensure 'scikit-learn' is installed and the model file is not corrupted. Details: {e}")
        return None

def main():
    """Main function to run the Streamlit app."""
    st.set_page_config(page_title="Logistic Regression Late Delivery Predictor", layout="wide")
    st.title("📦 Logistic Regression Late Delivery Predictor")
    st.markdown("Enter shipment details to predict the Late Delivery Status (1 for Late, 0 for On-Time).")

    # 1. Load Model
    model = load_model(MODEL_FILE)
    if model is None:
        st.stop()

    # 2. Define Expected Features and Categorical Values
    # Based on analysis, the model likely dropped 'Asia-EU' and 'Air' as baselines.
    ROUTE_IDS = ['Domestic', 'Asia-EU', 'Asia-US', 'Europe-US']
    TRANSPORT_MODES = ['Truck', 'Sea', 'Air', 'Unknown']

    # The exact features the model was trained with (assuming standard one-hot encoding with drop_first=True)
    MODEL_FEATURES = [
        'Supplier_Quality_Score',
        'Cost_Per_Unit',
        'Lead_Time_Days',
        'Actual_Delivery_Duration',
        'Route_ID_Asia-US',
        'Route_ID_Domestic',
        'Route_ID_Europe-US',
        'Transport_Mode_Sea',
        'Transport_Mode_Truck',
        'Transport_Mode_Unknown'
    ]

    # 3. Create Input Form
    with st.form("prediction_form"):
        st.header("Shipment Input Data")

        # --- Numerical Inputs ---
        col1, col2, col3 = st.columns(3)
        with col1:
            supplier_quality = st.number_input(
                "Supplier Quality Score (0.0 to 1.0)",
                min_value=0.0, max_value=1.0, value=0.5, step=0.01
            )
        with col2:
            cost_per_unit = st.number_input(
                "Cost Per Unit",
                min_value=0.0, value=150.0, step=10.0
            )
        with col3:
            lead_time = st.number_input(
                "Contractual Lead Time (Days)",
                min_value=1, value=10, step=1
            )

        # --- Date Inputs for calculating Actual_Delivery_Duration ---
        st.markdown("---")
        st.subheader("Delivery Dates (Used to Calculate Actual Delivery Duration)")
        today = date.today()
        default_order_date = today - timedelta(days=15)
        default_delivery_date = today

        col4, col5 = st.columns(2)
        with col4:
            order_date = st.date_input("Order Date", value=default_order_date)
        with col5:
            delivery_date = st.date_input("Delivery Confirmation Date", value=default_delivery_date)

        if delivery_date < order_date:
            st.error("Delivery Date cannot be before the Order Date.")
            submitted = False
        else:
            actual_duration = (delivery_date - order_date).days
            st.info(f"Calculated Actual Delivery Duration: **{actual_duration} days**")


        # --- Categorical Inputs ---
        st.markdown("---")
        st.subheader("Route and Transport Details")
        col6, col7 = st.columns(2)
        with col6:
            route_id = st.selectbox(
                "Route ID",
                options=ROUTE_IDS, index=1 # Default to Asia-EU (the assumed baseline)
            )
        with col7:
            transport_mode = st.selectbox(
                "Transport Mode",
                options=TRANSPORT_MODES, index=2 # Default to Air (the assumed baseline)
            )

        # 4. Prediction Button
        st.markdown("---")
        submitted = st.form_submit_button("Predict Late Delivery Status")

    # 5. Prediction Logic
    if submitted and delivery_date >= order_date:
        # 5a. Create a DataFrame from the user input
        input_data = pd.DataFrame([{
            'Supplier_Quality_Score': supplier_quality,
            'Cost_Per_Unit': cost_per_unit,
            'Lead_Time_Days': lead_time,
            'Actual_Delivery_Duration': actual_duration,
            'Route_ID': route_id,
            'Transport_Mode': transport_mode
        }])

        # 5b. Apply One-Hot Encoding
        input_data_encoded = pd.get_dummies(
            input_data,
            columns=['Route_ID', 'Transport_Mode']
        )

        # 5c. Manually drop the baseline columns used during model training
        # If the Route_ID is 'Asia-EU', its dummy column 'Route_ID_Asia-EU' will be 1, and should be dropped.
        # If the Transport_Mode is 'Air', its dummy column 'Transport_Mode_Air' will be 1, and should be dropped.
        if 'Route_ID_Asia-EU' in input_data_encoded.columns:
            input_data_encoded = input_data_encoded.drop(columns=['Route_ID_Asia-EU'])
        if 'Transport_Mode_Air' in input_data_encoded.columns:
            input_data_encoded = input_data_encoded.drop(columns=['Transport_Mode_Air'])

        # 5d. Align columns to match the training data exactly
        try:
            prediction_df = input_data_encoded.reindex(columns=MODEL_FEATURES, fill_value=0)

            # 5e. Make Prediction
            prediction = model.predict(prediction_df)
            prediction_proba = model.predict_proba(prediction_df)

            # 5f. Display Results
            st.subheader("Prediction Result")
            if prediction[0] == 1:
                st.error("🚨 Predicted Status: LATE DELIVERY")
                st.markdown(f"**Probability of Late Delivery:** $ {prediction_proba[0][1]:.2f} $")
            else:
                st.success("✅ Predicted Status: ON-TIME DELIVERY")
                st.markdown(f"**Probability of On-Time Delivery:** $ {prediction_proba[0][0]:.2f} $")

            st.balloons()

        except Exception as e:
            st.error(f"An error occurred during prediction. This may indicate a mismatch between the model's expected features and the input features. Please check the model training process. Error: {e}")

if __name__ == "__main__":
    main()